import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import './globals.css';
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "XLJ_HLY",
  description: "Generated by create next app",
};

// 定义根布局组件，接受子组件作为参数
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 根布局组件，接受子组件作为参数，并使用ClerkProvider包裹子组件
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header>Root header</header> */}
        {/* <h1>Root h1</h1> */}
        <ClerkProvider>
          <Providers>
            {children}
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}